package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"
)

// keyringEntry is one record in keyring.json consumed by the forked
// MasterDnsVPN server.
type keyringEntry struct {
	Domain string `json:"domain"`
	Key    string `json:"key"`
	Method int    `json:"method"`
}

type keyringFile struct {
	Version   int            `json:"version"`
	Instances []keyringEntry `json:"instances"`
}

// RuntimeState is reported to the UI.
type RuntimeState struct {
	Status      string `json:"status"`
	Running     bool   `json:"running"`
	PID         int    `json:"pid,omitempty"`
	MemoryBytes int64  `json:"memory_bytes,omitempty"`
	StartedAt   string `json:"started_at,omitempty"`
	ExitedAt    string `json:"exited_at,omitempty"`
	ExitError   string `json:"exit_error,omitempty"`
}

// serverManager supervises the single MasterDnsVPN server process and keeps
// keyring.json in sync with the panel instances.
type serverManager struct {
	mu           sync.Mutex
	binary       string
	runtimeDir   string
	keyringPath  string
	configPath   string
	cmd          *exec.Cmd
	pid          int
	startedAt    time.Time
	exitedAt     time.Time
	exitErr      string
	lastApplyErr string
}

func newServerManager(runtimeDir string) *serverManager {
	bin := os.Getenv("MASTERDNS_BIN")
	if bin == "" {
		bin = "/usr/local/bin/masterdns-server"
	}
	return &serverManager{
		binary:      bin,
		runtimeDir:  runtimeDir,
		keyringPath: filepath.Join(runtimeDir, "keyring.json"),
		configPath:  filepath.Join(runtimeDir, "server_config.toml"),
	}
}

// writeKeyring renders keyring.json + a base server_config.toml from the
// current instances.
func (m *serverManager) writeKeyring(instances []Instance) error {
	if err := os.MkdirAll(m.runtimeDir, 0o755); err != nil {
		return err
	}
	kf := keyringFile{Version: 1}
	for _, ins := range instances {
		kf.Instances = append(kf.Instances, keyringEntry{
			Domain: ins.Domain,
			Key:    ins.Key,
			Method: ins.Method,
		})
	}
	raw, err := json.MarshalIndent(kf, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(m.keyringPath, raw, 0o600); err != nil {
		return err
	}
	return m.ensureServerConfig()
}

// ensureServerConfig writes a server_config.toml that points the forked
// server at keyring.json. The server derives DOMAIN + per-domain codecs
// from the keyring, so the panel only manages keyring.json afterwards.
func (m *serverManager) ensureServerConfig() error {
	if _, err := os.Stat(m.configPath); err == nil {
		return nil // keep admin-tuned config
	}
	tmpl := fmt.Sprintf(`# Generated by zanoza-panel. Per-domain keys live in keyring.json.
KEYRING_FILE = "%s"
UDP_HOST = "0.0.0.0"
UDP_PORT = 53
DNS_UPSTREAM_SERVERS = ["1.1.1.1:53", "1.0.0.1:53"]
LOG_LEVEL = "INFO"
`, m.keyringPath)
	return os.WriteFile(m.configPath, []byte(tmpl), 0o644)
}

// apply syncs the keyring then reloads or (re)starts the server.
func (m *serverManager) apply(instances []Instance) error {
	if err := m.writeKeyring(instances); err != nil {
		return err
	}
	m.mu.Lock()
	running := m.cmd != nil && m.cmd.Process != nil && m.pid != 0
	pid := m.pid
	m.mu.Unlock()

	if len(instances) == 0 {
		// Nothing to serve; stop the process if it's up.
		m.stop()
		return nil
	}
	if running {
		// Ask the server to reload keyring.json in place.
		_ = syscall.Kill(pid, syscall.SIGHUP)
		return nil
	}
	return m.start()
}

func (m *serverManager) start() error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.cmd != nil && m.cmd.Process != nil {
		return nil
	}
	if _, err := os.Stat(m.binary); err != nil {
		m.lastApplyErr = "server binary not found: " + m.binary
		return fmt.Errorf("%s", m.lastApplyErr)
	}
	cmd := exec.Command(m.binary, "-config", m.configPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		m.lastApplyErr = err.Error()
		return err
	}
	m.cmd = cmd
	m.pid = cmd.Process.Pid
	m.startedAt = time.Now()
	m.exitErr = ""
	m.lastApplyErr = ""
	go m.reap(cmd)
	return nil
}

func (m *serverManager) reap(cmd *exec.Cmd) {
	err := cmd.Wait()
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.cmd == cmd {
		m.cmd = nil
		m.pid = 0
		m.exitedAt = time.Now()
		if err != nil {
			m.exitErr = err.Error()
		}
	}
}

func (m *serverManager) stop() {
	m.mu.Lock()
	cmd := m.cmd
	pid := m.pid
	m.mu.Unlock()
	if cmd == nil || pid == 0 {
		return
	}
	_ = syscall.Kill(pid, syscall.SIGTERM)
	done := make(chan struct{})
	go func() {
		_ = cmd.Wait()
		close(done)
	}()
	select {
	case <-done:
	case <-time.After(8 * time.Second):
		_ = cmd.Process.Kill()
	}
	m.mu.Lock()
	if m.cmd == cmd {
		m.cmd = nil
		m.pid = 0
		m.exitedAt = time.Now()
	}
	m.mu.Unlock()
}

func (m *serverManager) restart(instances []Instance) error {
	m.stop()
	if len(instances) == 0 {
		return nil
	}
	if err := m.writeKeyring(instances); err != nil {
		return err
	}
	return m.start()
}

func (m *serverManager) state() RuntimeState {
	m.mu.Lock()
	defer m.mu.Unlock()
	st := RuntimeState{}
	if m.cmd != nil && m.pid != 0 {
		st.Running = true
		st.Status = "running"
		st.PID = m.pid
		st.StartedAt = m.startedAt.UTC().Format(time.RFC3339)
		st.MemoryBytes = processMemoryBytes(m.pid)
	} else {
		st.Status = "stopped"
		if m.lastApplyErr != "" {
			st.ExitError = m.lastApplyErr
		} else if m.exitErr != "" {
			st.ExitError = m.exitErr
		}
		if !m.exitedAt.IsZero() {
			st.ExitedAt = m.exitedAt.UTC().Format(time.RFC3339)
		}
	}
	return st
}

// processMemoryBytes reads RSS from /proc on Linux; best-effort elsewhere.
func processMemoryBytes(pid int) int64 {
	if runtime.GOOS != "linux" || pid <= 0 {
		return 0
	}
	raw, err := os.ReadFile(fmt.Sprintf("/proc/%d/statm", pid))
	if err != nil {
		return 0
	}
	fields := strings.Fields(string(raw))
	if len(fields) < 2 {
		return 0
	}
	rssPages, err := strconv.ParseInt(fields[1], 10, 64)
	if err != nil {
		return 0
	}
	return rssPages * int64(os.Getpagesize())
}
