// ==============================================================================
// MasterDnsVPN
// Author: MasterkinG32
// Github: https://github.com/masterking32
// Year: 2026
// ==============================================================================

package security

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"masterdnsvpn-go/internal/config"
)

type EncryptionKeyInfo struct {
	MethodID   int
	MethodName string
	Key        string
	Path       string
	Loaded     bool
	Generated  bool
}

const maxEncryptionKeyFileBytes = 4 << 10

func EnsureServerEncryptionKey(cfg config.ServerConfig) (EncryptionKeyInfo, error) {
	info := EncryptionKeyInfo{
		MethodID:   cfg.DataEncryptionMethod,
		MethodName: EncryptionMethodName(cfg.DataEncryptionMethod),
		Path:       cfg.EncryptionKeyPath(),
	}

	requiredLength := requiredKeyLength(cfg.DataEncryptionMethod)
	key, exists, err := loadExistingEncryptionKey(info.Path, requiredLength)
	if err != nil {
		return info, err
	}
	if exists {
		info.Key = key
		info.Loaded = true
		return info, nil
	}

	key, err = generateHexText(requiredLength)
	if err != nil {
		return info, fmt.Errorf("generate encryption key: %w", err)
	}
	created, err := writeKeyAtomicNoReplace(info.Path, []byte(key))
	if err != nil {
		return info, fmt.Errorf("write encryption key file %s: %w", info.Path, err)
	}
	if !created {
		// Another process won the atomic publish race. Load its complete key
		// instead of starting with a private key that is no longer on disk.
		key, exists, err = loadExistingEncryptionKey(info.Path, requiredLength)
		if err != nil {
			return info, err
		}
		if !exists {
			return info, fmt.Errorf("encryption key file %s disappeared during concurrent creation", info.Path)
		}
		info.Key = key
		info.Loaded = true
		return info, nil
	}

	info.Key = key
	info.Generated = true
	return info, nil
}

func loadExistingEncryptionKey(path string, requiredLength int) (string, bool, error) {
	pathInfo, err := os.Lstat(path)
	if os.IsNotExist(err) {
		return "", false, nil
	}
	if err != nil {
		return "", false, fmt.Errorf("inspect encryption key file %s: %w", path, err)
	}
	if pathInfo.Mode()&os.ModeSymlink != 0 || !pathInfo.Mode().IsRegular() {
		return "", false, fmt.Errorf("encryption key path %s must be a regular non-symlink file", path)
	}

	file, err := os.Open(path)
	if err != nil {
		return "", false, fmt.Errorf("read encryption key file %s: %w", path, err)
	}
	defer func() { _ = file.Close() }()
	openedInfo, err := file.Stat()
	if err != nil {
		return "", false, fmt.Errorf("inspect opened encryption key file %s: %w", path, err)
	}
	if !openedInfo.Mode().IsRegular() || !os.SameFile(pathInfo, openedInfo) {
		return "", false, fmt.Errorf("encryption key path %s changed while opening", path)
	}
	raw, err := io.ReadAll(io.LimitReader(file, maxEncryptionKeyFileBytes+1))
	if err != nil {
		return "", false, fmt.Errorf("read encryption key file %s: %w", path, err)
	}
	if len(raw) > maxEncryptionKeyFileBytes {
		return "", false, fmt.Errorf("encryption key file %s exceeds the %d-byte size limit", path, maxEncryptionKeyFileBytes)
	}
	key := strings.TrimSpace(string(raw))
	if len(key) != requiredLength {
		return "", false, fmt.Errorf("encryption key file %s has invalid length %d, want %d; refusing to rotate an existing key", path, len(key), requiredLength)
	}
	if err := file.Chmod(0o600); err != nil {
		return "", false, fmt.Errorf("secure encryption key file %s: %w", path, err)
	}
	currentInfo, err := os.Lstat(path)
	if err != nil || currentInfo.Mode()&os.ModeSymlink != 0 || !os.SameFile(openedInfo, currentInfo) {
		return "", false, fmt.Errorf("encryption key path %s changed while reading", path)
	}
	return key, true, nil
}

func writeKeyAtomicNoReplace(path string, raw []byte) (created bool, err error) {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return false, err
	}
	tmpName := tmp.Name()
	defer func() {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
	}()
	if err = tmp.Chmod(0o600); err != nil {
		return false, err
	}
	if _, err = tmp.Write(raw); err != nil {
		return false, err
	}
	if err = tmp.Sync(); err != nil {
		return false, err
	}
	if err = tmp.Close(); err != nil {
		return false, err
	}
	// Linking a fully-written same-directory file publishes it atomically and
	// fails if the destination already exists. Rename would overwrite a key
	// concurrently generated by another process.
	if err = os.Link(tmpName, path); err != nil {
		if _, statErr := os.Lstat(path); statErr == nil {
			return false, nil
		}
		return false, err
	}
	if d, openErr := os.Open(dir); openErr == nil {
		_ = d.Sync()
		_ = d.Close()
	}
	return true, nil
}

func EncryptionMethodName(methodID int) string {
	switch methodID {
	case 0:
		return "NONE"
	case 1:
		return "XOR"
	case 2:
		return "ChaCha20"
	case 3:
		return "AES-128-GCM"
	case 4:
		return "AES-192-GCM"
	case 5:
		return "AES-256-GCM"
	default:
		return "UNKNOWN"
	}
}

func requiredKeyLength(methodID int) int {
	switch methodID {
	case 3:
		return 16
	case 4:
		return 24
	default:
		return 32
	}
}

func generateHexText(length int) (string, error) {
	if length <= 0 {
		return "", nil
	}
	buf := make([]byte, (length+1)/2)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf)[:length], nil
}
